name: unipapers_project
description: "A Flutter project made for public researches repository, much like GitHub, but for researches. Made, thought, and developed specifically by college students."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  file_picker: ^8.0.3
  path_provider: ^2.0.11
  open_file: ^3.3.2
  document_file_save_plus: ^2.0.0
  easy_mask: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/