List<String> coursesList = <String>[
  "CURSO",
  "Administração",
  "Análise e Desenvolvimento de Sistemas",
  "Arquitetura e Urbanismo",
  "Artes Visuais",
  "Biomedicina",
  "Ciência de Dados e Inteligência Artificial",
  "Ciências Biológicas (Bacharelado)",
  "Ciências Biológicas (Licenciatura)",
  "Ciências Contábeis",
  "Ciências Econômicas",
  "Comércio Exterior",
  "Dança",
  "Design",
  "Design de Interiores",
  "Direito",
  "Educação Física - Bacharelado",
  "Educação Física - Licenciatura",
  "Enfermagem",
  "Engenharia Agronômica",
  "Engenharia Ambiental",
  "Engenharia Civil",
  "Engenharia da Computação",
  "Engenharia de Alimentos",
  "Engenharia de Bioprocessos e Biotecnologia",
  "Engenharia de Controle e Automação",
  "Engenharia de Produção",
  "Engenharia Elétrica",
  "Engenharia Mecânica",
  "Engenharia Química",
  "Estética e Cosmética",
  "Farmácia",
  "Filosofia",
  "Fisioterapia",
  "Fonoaudiologia",
  "Gastronomia",
  "Gestão Comercial",
  "Gestão da Qualidade",
  "Gestão de Equinocultura",
  "Gestão de Recursos Humanos",
  "Gestão Financeira",
  "História",
  "Hotelaria",
  "Jogos Digitais",
  "Jornalismo",
  "Letras: Português/Inglês",
  "Logística",
  "Marketing",
  "Matemática",
  "Medicina Veterinária",
  "Moda",
  "Música",
  "Nutrição",
  "Odontologia",
  "Pedagogia",
  "Pedagogia (integral)",
  "Processos Gerenciais",
  "Psicologia",
  "Publicidade e Propaganda",
  "Química",
  "Química Industrial",
  "Relações Internacionais",
  "Relações Públicas",
  "Teatro",
  "Terapia Ocupacional"
];
